### PR TITLE
Remove Hazelcast

### PR DESCRIPTION
**Pull request by piyumaldk**
## Purpose
As we have deprecated the Hazelcast based distributed caching use cases in APIM, removing the Hazelcast dependency from wso2-synapse repository.

Fixes https://github.com/wso2/api-manager/issues/513

### CODE REVIEW

**Review by tharindu1st — APPROVED** [review]

**Comment by GDLMadushanka** [comment]
All theese commits can be merged to a single commit.

**Review by malakaganga — COMMENTED** [review]
Shall we squash commits and leave only meaningful commits also shall we add a meaningful commit subject and add the issue url to the commit message body.

**Comment by piyumaldk** [comment]
> All these commits can be merged to a single commit.

Will make sure to address this in future commits since this is already merged. Thanks for the input.

**Comment by piyumaldk** [comment]
> Shall we squash commits and leave only meaningful commits also shall we add a meaningful commit subject and add the issue url to the commit message body.

Will make sure to address this in future commits since this is already merged. Thanks for the input.

**Pull request merged**
