### PR TITLE
fix for string json

### PR DESCRIPTION
**Pull request by Posejdon23**
https://wso2.org/jira/browse/ESBJAVA-4902

### CODE REVIEW

**Comment by Posejdon23** [comment]
This fix the problem of parsing response of type application/json with content like this:
"some text"
I don`t know how to write a good test for it. Please help me with that.

**Comment by riyafa** [comment]
Thanks for your contribution, and currently we are improving the fix in the newer version of ESB

**Comment by Posejdon23** [comment]
Thank you too. Which version will include fix for this bug?

Kamil Uchnast

28 cze 2017 07:22 "Riyafa Abdul Hameed" <notifications@github.com>
napisał(a):

**Comment by riyafa** [comment]
It will be fixed in EI 6.2.

**Comment by vinok88** [comment]
These changes are included in the https://github.com/wso2/wso2-synapse/pull/759 with some improvements. Thank you very much for the contribution.

**Pull request closed without merging**
