### PR TITLE
[6.1.1] Integrator : Message Processor : support parsing complex header elements

### PR DESCRIPTION
**Pull request by mathieubouchard**
## Purpose
When a message processor is parsing the SOAP header from a SOAP envelope persisted in a message store, the nested nodes from the headers are not added to the outgoing message.

For example, the following message :
```
<?xml version='1.0' encoding='utf-8'?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header>
    <MyCustomHeader xmlns="http://ca.example.com/MyCustomHeader">
      <NestedHeader>blabla</NestedHeader>
    </MyCustomHeader>
  </soapenv:Header>
  <soapenv:Body>
    <ns:Artefact xmlns:ns="http://ca.example.com/ws/Artefacts/2017/11">
      <ns:Archive>
        <ns:ArchiveName>EsbDeploy_1.0.0.car</ns:ArchiveName>
        <ns:ArchiveVersion>67463234</ns:ArchiveVersion>
      </ns:Archive>
    </ns:Artefact>
  </soapenv:Body>
</soapenv:Envelope>
```

Would be sent to the message processor endpoint as:
```
<?xml version='1.0' encoding='utf-8'?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header>
    <MyCustomHeader xmlns="http://ca.example.com/MyCustomHeader"/>
  </soapenv:Header>
  <soapenv:Body>
    <ns:Artefact xmlns:ns="http://ca.example.com/ws/Artefacts/2017/11">
      <ns:Archive>
        <ns:ArchiveName>EsbDeploy_1.0.0.car</ns:ArchiveName>
        <ns:ArchiveVersion>67463234</ns:ArchiveVersion>
      </ns:Archive>
    </ns:Artefact>
  </soapenv:Body>
</soapenv:Envelope>
```

## Goals
Completely parse the SOAP headers to send the complete message that was persisted to the message store.

## Approach
Just add the node to the created header block element

## Test environment
JDK 1.8
Windows 7 & RHEL6
H2 & Oracle

### CODE REVIEW

**Comment by bsenduran** [comment]
Hi @mathieubouchard 
Thank you for your contribution.

I tried a simple setup using a _InMemory_ store and tired both _forwarding message processor_ and _sampling message processor_ but I couldn't see any issues as you mentioned. (i.e backend receives the complete SOAP header)
I tried with the latest EI release : [update-21](https://github.com/wso2/product-ei/releases/tag/v6.1.1-update21)
Kindly let me know whether I have to something else too to reproduce this issue and verify the fix.
Regards
Senduran

**Comment by mathieubouchard** [comment]
Hi @bsenduran 

I don't know about the InMemory store, but the code must trigger a call to the MemoryConverter class as is done in the JMS store implementation.

We tried with the JMS Message Store and MB Message Store to store the data in the broker runtime.

**Comment by mathieubouchard** [comment]
Error when commenting, reopening issue

**Comment by bsenduran** [comment]
Hi @mathieubouchard ,
I have verified with JMS message store and the fix. It solves the issues hence merging the pull request.
Thanks again for your contribution.

**Pull request merged**
