### PR TITLE
Enable new transaction creation with use-existing-or-new action

### PR DESCRIPTION
**Pull request by prabushi**
Enabled new transaction creation for the "use-existing-or-new" action in Transaction mediator, which was disabled before. Same functionality of "new" action was added for "use-existing-or-new".

### CODE REVIEW

**Comment by milindaperera** [comment]
Does this fix have related Jira or Git issue?

**Comment by prabushi** [comment]
@milindaperera, No, this was identified while writing tests. Do I need to create a JIRA for this?

**Comment by milindaperera** [comment]
@prabushi  shall we create issue or add little description here

**Comment by milindaperera** [comment]
@prabushi Adding description is enough

**Comment by prabushi** [comment]
@milindaperera Updated the description.

**Pull request merged**
