### PR TITLE
Use URNString UUID for correlationId

### PR DESCRIPTION
**Pull request by isudana**
## Purpose
Fixing https://github.com/wso2/micro-integrator/issues/2212

### CODE REVIEW

**Review by sdkottegoda — APPROVED** [review]

**Comment by sdkottegoda** [comment]
Should we state this in docs, mentioning that the pattern of the correlation ids has changed?

**Comment by isudana** [comment]
> Should we state this in docs, mentioning that the pattern of the correlation ids has changed?

Have we mentioned the pattern in the docs, wondering whether people are interested in it?

**Comment by sdkottegoda** [comment]
> > Should we state this in docs, mentioning that the pattern of the correlation ids has changed?
> 
> Have we mentioned the pattern in the docs, wondering whether people are interested in it?

https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/observability/#reading-correlation-logs

**Comment by isudana** [comment]
I am thinking of a different solution to fix the issue wso2/micro-integrator#2212. Hence closing this PR.

**Pull request closed without merging**
