### PR TITLE
ESBJAVA-3493 - Warning log message was added for aggregate mediator time...

### PR DESCRIPTION
**Pull request by ravindraranwala**
...out scenario.

### CODE REVIEW

**Comment by isudana** [comment]
Hi Chanaka,

We are no longer using develop branch now. Fix need to be merged to wso2 branch.

**Comment by chanakaudaya** [comment]
Hi Isuru,
Noted. I have reverted the commit from develop branch. 
@ravindraranwala : please send the PR to master branch.

**Comment by ravindraranwala** [comment]
A new Pull request https://github.com/wso2/wso2-synapse/pull/249 was sent as per the request pointing the master branch. Please merge this and resolve the public jira issue.

**Comment by ravindraranwala** [comment]
Please merge this pull request https://github.com/wso2/wso2-synapse/pull/250. I have removed all the unnecessary changes here.

**Pull request merged**
