### PR TITLE
Script improvement

### PR DESCRIPTION
**Pull request by Buddhima**
* ```setProperty``` improved so configuration can define to which scope the property get saved
* ```removeProperty``` to remove a property in a given scope

Refer: https://wso2.org/jira/browse/ESBJAVA-4380

### CODE REVIEW

**Comment by arabsoheyl** [comment]
I am testing this feature, in WSO2ESB-5.0.0 and get this error:
` Can't find method org.apache.synapse.core.axis2.Axis2MessageContext.setProperty(string,string,string).`

**Comment by Buddhima** [comment]
@arabsoheyl Can you add the configuration which is giving the error?

**Comment by arabsoheyl** [comment]
I use this:
<script language="js">mc..setProperty("HTTP_METHOD","POST", "axis2");</script>

**Comment by arabsoheyl** [comment]
> @arabsoheyl Can you add the configuration which is giving the error?

I use this:
<script language="js">mc..setProperty("HTTP_METHOD","POST", "axis2");</script>

**Pull request merged**
